
package view;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Model;
/**
 *
 * @author rogerguedez
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public CardLayout cLayout;
    public String currentView;
    public Screen() {
        initComponents();
        cLayout = (CardLayout) (contentLayout.getLayout());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        sideBar = new javax.swing.JPanel();
        productsButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        exitButton = new javax.swing.JButton();
        calcButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        kitchenReportButton = new javax.swing.JButton();
        supervisorReportButton = new javax.swing.JButton();
        inventoryReportButton = new javax.swing.JButton();
        productLoseReportButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        providersButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        contentLayout = new javax.swing.JPanel();
        dashboardView = new javax.swing.JPanel();
        helloText = new javax.swing.JLabel();
        roleText = new javax.swing.JLabel();
        tableRegisterView = new javax.swing.JPanel();
        tableRegisterTitle = new javax.swing.JLabel();
        newRegistButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registerTable = new javax.swing.JTable();
        newProvider = new javax.swing.JPanel();
        newProviderTitle = new javax.swing.JLabel();
        newProviderDocText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newProviderNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newProviderSurnameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        newProviderPhoneText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newProviderMailText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        newProviderAddressText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        newProviderBtn = new javax.swing.JButton();
        newProduct = new javax.swing.JPanel();
        newProductTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newProductNameText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newProductPriceText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        newProductDecrAvText = new javax.swing.JTextField();
        newProductBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        newProductProviderSelect = new javax.swing.JComboBox<>();
        newInventory = new javax.swing.JPanel();
        newInventoryTitle = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newInvKgInitial = new javax.swing.JTextField();
        newInvProductSelect = new javax.swing.JComboBox<>();
        newInvProductBtn = new javax.swing.JButton();
        calcDecrease = new javax.swing.JPanel();
        calcDecreaseTitle = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        calcDecreaseProductSelect = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        calcDecreaseUseKg = new javax.swing.JTextField();
        calcDecreaseBtn = new javax.swing.JButton();
        calcDecreaseCurrentKg = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        calcDecreaseAverage = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        calcDecreaseReal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        calcDecreaseDiff = new javax.swing.JLabel();
        calcDecreaseDateSelect = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        calcDecreaseCurrentInv = new javax.swing.JLabel();
        calcDecreaseNewInv = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        calcDecreaseAverageWeight = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(101, 183, 65));

        productsButton.setBackground(new java.awt.Color(101, 183, 65));
        productsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productsButton.setForeground(new java.awt.Color(245, 245, 245));
        productsButton.setText("PRODUCTOS");
        productsButton.setBorderPainted(false);
        productsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productsButton.setName("Product"); // NOI18N
        productsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsButtonActionPerformed(evt);
            }
        });

        inventoryButton.setBackground(new java.awt.Color(101, 183, 65));
        inventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventoryButton.setForeground(new java.awt.Color(245, 245, 245));
        inventoryButton.setText("INVENTARIO");
        inventoryButton.setBorderPainted(false);
        inventoryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryButton.setName("Inventory"); // NOI18N
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(101, 183, 65));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(245, 245, 245));
        exitButton.setText("SALIR");
        exitButton.setBorderPainted(false);
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        calcButton.setBackground(new java.awt.Color(101, 183, 65));
        calcButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calcButton.setForeground(new java.awt.Color(245, 245, 245));
        calcButton.setText("CALCULAR MERMA");
        calcButton.setBorderPainted(false);
        calcButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calcButton.setName("Calc"); // NOI18N
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        kitchenReportButton.setBackground(new java.awt.Color(101, 183, 65));
        kitchenReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kitchenReportButton.setForeground(new java.awt.Color(245, 245, 245));
        kitchenReportButton.setText("MOVIMIENTOS EN COCINA");
        kitchenReportButton.setBorderPainted(false);
        kitchenReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitchenReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenReportButtonActionPerformed(evt);
            }
        });

        supervisorReportButton.setBackground(new java.awt.Color(101, 183, 65));
        supervisorReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supervisorReportButton.setForeground(new java.awt.Color(245, 245, 245));
        supervisorReportButton.setText("MOVIMIENTOS POR ENCARGADO");
        supervisorReportButton.setBorderPainted(false);
        supervisorReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supervisorReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorReportButtonActionPerformed(evt);
            }
        });

        inventoryReportButton.setBackground(new java.awt.Color(101, 183, 65));
        inventoryReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventoryReportButton.setForeground(new java.awt.Color(245, 245, 245));
        inventoryReportButton.setText("MOVIMIENTOS DE INVENTARIO");
        inventoryReportButton.setBorderPainted(false);
        inventoryReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryReportButtonActionPerformed(evt);
            }
        });

        productLoseReportButton.setBackground(new java.awt.Color(101, 183, 65));
        productLoseReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productLoseReportButton.setForeground(new java.awt.Color(245, 245, 245));
        productLoseReportButton.setText("MERMA POR PRODUCTO");
        productLoseReportButton.setBorderPainted(false);
        productLoseReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productLoseReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productLoseReportButtonActionPerformed(evt);
            }
        });

        configButton.setBackground(new java.awt.Color(101, 183, 65));
        configButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        configButton.setForeground(new java.awt.Color(245, 245, 245));
        configButton.setText("MANTENIMIENTO");
        configButton.setBorderPainted(false);
        configButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(101, 183, 65));
        helpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(245, 245, 245));
        helpButton.setText("AYUDA");
        helpButton.setBorderPainted(false);
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        providersButton.setBackground(new java.awt.Color(101, 183, 65));
        providersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        providersButton.setForeground(new java.awt.Color(245, 245, 245));
        providersButton.setText("PROVEEDORES");
        providersButton.setBorderPainted(false);
        providersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        providersButton.setName("Provider"); // NOI18N
        providersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providersButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(101, 183, 65));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(245, 245, 245));
        homeButton.setText("TABLERO");
        homeButton.setBorderPainted(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(calcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(kitchenReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(supervisorReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(inventoryReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(configButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(productLoseReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(providersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(providersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(kitchenReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supervisorReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLoseReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(configButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        contentLayout.setBackground(new java.awt.Color(255, 255, 255));
        contentLayout.setLayout(new java.awt.CardLayout());

        dashboardView.setBackground(new java.awt.Color(255, 255, 255));

        helloText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        helloText.setForeground(new java.awt.Color(101, 183, 65));
        helloText.setText("A");
        helloText.setMaximumSize(new java.awt.Dimension(550, 512));
        helloText.setName("newProductTitle"); // NOI18N

        roleText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        roleText.setForeground(new java.awt.Color(255, 181, 52));
        roleText.setText("B");
        roleText.setMaximumSize(new java.awt.Dimension(550, 512));
        roleText.setName("newProductTitle"); // NOI18N

        javax.swing.GroupLayout dashboardViewLayout = new javax.swing.GroupLayout(dashboardView);
        dashboardView.setLayout(dashboardViewLayout);
        dashboardViewLayout.setHorizontalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardViewLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(899, Short.MAX_VALUE))
        );
        dashboardViewLayout.setVerticalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardViewLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(helloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(788, Short.MAX_VALUE))
        );

        contentLayout.add(dashboardView, "dashboardView");

        tableRegisterView.setBackground(new java.awt.Color(255, 255, 255));

        tableRegisterTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tableRegisterTitle.setForeground(new java.awt.Color(51, 51, 51));
        tableRegisterTitle.setText("Titulo");
        tableRegisterTitle.setMaximumSize(new java.awt.Dimension(550, 512));

        newRegistButton.setBackground(new java.awt.Color(101, 183, 65));
        newRegistButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newRegistButton.setForeground(new java.awt.Color(245, 245, 245));
        newRegistButton.setText("NUEVO");
        newRegistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRegistButtonActionPerformed(evt);
            }
        });

        registerTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(registerTable);

        javax.swing.GroupLayout tableRegisterViewLayout = new javax.swing.GroupLayout(tableRegisterView);
        tableRegisterView.setLayout(tableRegisterViewLayout);
        tableRegisterViewLayout.setHorizontalGroup(
            tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableRegisterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tableRegisterViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tableRegisterViewLayout.createSequentialGroup()
                        .addComponent(tableRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 649, Short.MAX_VALUE)
                        .addComponent(newRegistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        tableRegisterViewLayout.setVerticalGroup(
            tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableRegisterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newRegistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        contentLayout.add(tableRegisterView, "tableRegisterView");

        newProvider.setBackground(new java.awt.Color(255, 255, 255));
        newProvider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newProvider.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newProviderTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newProviderTitle.setForeground(new java.awt.Color(51, 51, 51));
        newProviderTitle.setText("Nuevo proveedor");
        newProviderTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newProviderTitle.setName("newProductTitle"); // NOI18N

        newProviderDocText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderDocText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderDocTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Rif/Cédula");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        newProviderNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderNameTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");

        newProviderSurnameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderSurnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderSurnameTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Teléfono");

        newProviderPhoneText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderPhoneTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Correo");

        newProviderMailText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderMailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderMailTextActionPerformed(evt);
            }
        });

        newProviderAddressText.setColumns(20);
        newProviderAddressText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderAddressText.setRows(5);
        jScrollPane2.setViewportView(newProviderAddressText);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Dirección");

        newProviderBtn.setBackground(new java.awt.Color(255, 181, 52));
        newProviderBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newProviderBtn.setForeground(new java.awt.Color(245, 245, 245));
        newProviderBtn.setText("GUARDAR");

        javax.swing.GroupLayout newProviderLayout = new javax.swing.GroupLayout(newProvider);
        newProvider.setLayout(newProviderLayout);
        newProviderLayout.setHorizontalGroup(
            newProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProviderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newProviderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProviderDocText)
                    .addComponent(jLabel1)
                    .addComponent(newProviderNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(newProviderSurnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(newProviderPhoneText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(newProviderMailText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProviderLayout.createSequentialGroup()
                .addContainerGap(467, Short.MAX_VALUE)
                .addComponent(newProviderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        newProviderLayout.setVerticalGroup(
            newProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProviderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newProviderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderDocText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderSurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderMailText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(newProviderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        contentLayout.add(newProvider, "newProvider");

        newProduct.setBackground(new java.awt.Color(255, 255, 255));
        newProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newProduct.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newProductTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newProductTitle.setForeground(new java.awt.Color(51, 51, 51));
        newProductTitle.setText("Nuevo producto");
        newProductTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newProductTitle.setName("newProductTitle"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre");

        newProductNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductNameTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Precio");

        newProductPriceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductPriceTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Merma Promedio");

        newProductDecrAvText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductDecrAvText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductDecrAvTextActionPerformed(evt);
            }
        });

        newProductBtn.setBackground(new java.awt.Color(255, 181, 52));
        newProductBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newProductBtn.setForeground(new java.awt.Color(245, 245, 245));
        newProductBtn.setText("GUARDAR");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Proveedor");

        newProductProviderSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout newProductLayout = new javax.swing.GroupLayout(newProduct);
        newProduct.setLayout(newProductLayout);
        newProductLayout.setHorizontalGroup(
            newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProductLayout.createSequentialGroup()
                .addContainerGap(463, Short.MAX_VALUE)
                .addComponent(newProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
            .addGroup(newProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newProductProviderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newProductNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(newProductPriceText)
                        .addComponent(jLabel8)
                        .addComponent(newProductDecrAvText)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newProductLayout.setVerticalGroup(
            newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProductNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProductPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProductDecrAvText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(newProductProviderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(newProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        contentLayout.add(newProduct, "newProduct");

        newInventory.setBackground(new java.awt.Color(255, 255, 255));
        newInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newInventory.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newInventoryTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newInventoryTitle.setForeground(new java.awt.Color(51, 51, 51));
        newInventoryTitle.setText("Añadir a inventario");
        newInventoryTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newInventoryTitle.setName("newProductTitle"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Producto");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Cantidad Inicial (Kg)");

        newInvKgInitial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newInvKgInitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newInvKgInitialActionPerformed(evt);
            }
        });

        newInvProductSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        newInvProductBtn.setBackground(new java.awt.Color(255, 181, 52));
        newInvProductBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newInvProductBtn.setForeground(new java.awt.Color(245, 245, 245));
        newInvProductBtn.setText("GUARDAR");

        javax.swing.GroupLayout newInventoryLayout = new javax.swing.GroupLayout(newInventory);
        newInventory.setLayout(newInventoryLayout);
        newInventoryLayout.setHorizontalGroup(
            newInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newInventoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(newInvKgInitial)
                    .addComponent(jLabel12)
                    .addComponent(newInvProductSelect, 0, 474, Short.MAX_VALUE))
                .addContainerGap(472, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInventoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newInvProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409))
        );
        newInventoryLayout.setVerticalGroup(
            newInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newInventoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newInvProductSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newInvKgInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(newInvProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        contentLayout.add(newInventory, "newInventory");

        calcDecrease.setBackground(new java.awt.Color(255, 255, 255));
        calcDecrease.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calcDecrease.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        calcDecreaseTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        calcDecreaseTitle.setForeground(new java.awt.Color(51, 51, 51));
        calcDecreaseTitle.setText("Calcular merma");
        calcDecreaseTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        calcDecreaseTitle.setName("newProductTitle"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Producto");

        calcDecreaseProductSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcDecreaseProductSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcDecreaseProductSelectActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Cantidad a utilizar (Kg)");

        calcDecreaseUseKg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcDecreaseUseKg.setEnabled(false);
        calcDecreaseUseKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcDecreaseUseKgActionPerformed(evt);
            }
        });

        calcDecreaseBtn.setBackground(new java.awt.Color(255, 181, 52));
        calcDecreaseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calcDecreaseBtn.setForeground(new java.awt.Color(245, 245, 245));
        calcDecreaseBtn.setText("REGISTRAR");

        calcDecreaseCurrentKg.setFont(new java.awt.Font("Segoe UI", 1, 74)); // NOI18N
        calcDecreaseCurrentKg.setForeground(new java.awt.Color(101, 183, 65));
        calcDecreaseCurrentKg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcDecreaseCurrentKg.setEnabled(false);
        calcDecreaseCurrentKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcDecreaseCurrentKgActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Merma promedio");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Peso actual (Kg)");

        calcDecreaseAverage.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        calcDecreaseAverage.setForeground(new java.awt.Color(255, 181, 52));
        calcDecreaseAverage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calcDecreaseAverage.setText("--");
        calcDecreaseAverage.setName("num_3"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Merma real");

        calcDecreaseReal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        calcDecreaseReal.setForeground(new java.awt.Color(101, 183, 65));
        calcDecreaseReal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calcDecreaseReal.setText("--");
        calcDecreaseReal.setName("num_5"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Fecha de ingreso");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Diferencia");

        calcDecreaseDiff.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        calcDecreaseDiff.setForeground(new java.awt.Color(212, 28, 34));
        calcDecreaseDiff.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calcDecreaseDiff.setText("--");
        calcDecreaseDiff.setName("num_6"); // NOI18N

        calcDecreaseDateSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcDecreaseDateSelect.setEnabled(false);
        calcDecreaseDateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcDecreaseDateSelectActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Inventario actual");

        calcDecreaseCurrentInv.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        calcDecreaseCurrentInv.setForeground(new java.awt.Color(255, 181, 52));
        calcDecreaseCurrentInv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calcDecreaseCurrentInv.setText("--");
        calcDecreaseCurrentInv.setName("num_1"); // NOI18N

        calcDecreaseNewInv.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        calcDecreaseNewInv.setForeground(new java.awt.Color(255, 181, 52));
        calcDecreaseNewInv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calcDecreaseNewInv.setText("--");
        calcDecreaseNewInv.setName("num_2"); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Nuevo inventario");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Peso merma promedio");

        calcDecreaseAverageWeight.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        calcDecreaseAverageWeight.setForeground(new java.awt.Color(255, 181, 52));
        calcDecreaseAverageWeight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calcDecreaseAverageWeight.setText("--");
        calcDecreaseAverageWeight.setName("num_4"); // NOI18N

        javax.swing.GroupLayout calcDecreaseLayout = new javax.swing.GroupLayout(calcDecrease);
        calcDecrease.setLayout(calcDecreaseLayout);
        calcDecreaseLayout.setHorizontalGroup(
            calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcDecreaseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcDecreaseUseKg)
                            .addGroup(calcDecreaseLayout.createSequentialGroup()
                                .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(calcDecreaseDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(calcDecreaseProductSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(calcDecreaseCurrentInv)
                            .addComponent(jLabel21)
                            .addComponent(calcDecreaseNewInv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calcDecreaseCurrentKg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calcDecreaseAverage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calcDecreaseReal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calcDecreaseDiff, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calcDecreaseAverageWeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
            .addGroup(calcDecreaseLayout.createSequentialGroup()
                .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(calcDecreaseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(calcDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcDecreaseLayout.setVerticalGroup(
            calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcDecreaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcDecreaseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addComponent(calcDecreaseCurrentKg, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcDecreaseAverage)
                        .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calcDecreaseLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel20))
                            .addGroup(calcDecreaseLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calcDecreaseAverageWeight))))
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addComponent(calcDecreaseProductSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcDecreaseDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcDecreaseUseKg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(calcDecreaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(calcDecreaseCurrentInv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addGap(8, 8, 8)
                        .addComponent(calcDecreaseNewInv))
                    .addGroup(calcDecreaseLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcDecreaseReal)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcDecreaseDiff)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(calcDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        contentLayout.add(calcDecrease, "calcDecrease");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void kitchenReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitchenReportButtonActionPerformed

    private void supervisorReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervisorReportButtonActionPerformed

    private void inventoryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryReportButtonActionPerformed

    private void productLoseReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productLoseReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productLoseReportButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtonActionPerformed

    private void providersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providersButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        tableRegisterTitle.setText("Proveedores");
        currentView = providersButton.getName();
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconProvider.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
        System.out.println(tableRegisterTitle.getIcon());
        /*
        contentLayout.removeAll();
        contentLayout.add(dashboardView);
        contentLayout.repaint();
        contentLayout.revalidate();
        */
    }//GEN-LAST:event_providersButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "dashboardView");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void productsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        currentView = productsButton.getName();
        
        tableRegisterTitle.setText("Productos");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconProduct.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_productsButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        currentView = inventoryButton.getName();
        tableRegisterTitle.setText("Inventario");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconInventory.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_calcButtonActionPerformed

    private void newRegistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRegistButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_newRegistButtonActionPerformed

    private void newProviderDocTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderDocTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderDocTextActionPerformed

    private void newProviderNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderNameTextActionPerformed

    private void newProviderSurnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderSurnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderSurnameTextActionPerformed

    private void newProviderPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderPhoneTextActionPerformed

    private void newProviderMailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderMailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderMailTextActionPerformed

    private void newProductNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductNameTextActionPerformed

    private void newProductPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductPriceTextActionPerformed

    private void newProductDecrAvTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductDecrAvTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductDecrAvTextActionPerformed

    private void newInvKgInitialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newInvKgInitialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newInvKgInitialActionPerformed

    private void calcDecreaseUseKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcDecreaseUseKgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcDecreaseUseKgActionPerformed

    private void calcDecreaseProductSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcDecreaseProductSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcDecreaseProductSelectActionPerformed

    private void calcDecreaseCurrentKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcDecreaseCurrentKgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcDecreaseCurrentKgActionPerformed

    private void calcDecreaseDateSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcDecreaseDateSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcDecreaseDateSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }
    
    
    
    public static void clearForm(JPanel com) {
        for(Component control : com.getComponents())
        {
            if(control instanceof JTextField)
            {
                JTextField ctrl = (JTextField) control;
                ctrl.setText("");
            }
            else if (control instanceof JComboBox)
            {
                JComboBox ctrl = (JComboBox) control;
                ctrl.setSelectedIndex(0);
            }
            else if (control instanceof JLabel){
                JLabel ctrl = (JLabel) control;
                if(ctrl.getName() != null && ctrl.getName().contains("num_")){
                     ctrl.setText("--");
                }
               
            
            }
          
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton calcButton;
    public javax.swing.JPanel calcDecrease;
    public javax.swing.JLabel calcDecreaseAverage;
    public javax.swing.JLabel calcDecreaseAverageWeight;
    public javax.swing.JButton calcDecreaseBtn;
    public javax.swing.JLabel calcDecreaseCurrentInv;
    public javax.swing.JTextField calcDecreaseCurrentKg;
    public javax.swing.JComboBox<String> calcDecreaseDateSelect;
    public javax.swing.JLabel calcDecreaseDiff;
    public javax.swing.JLabel calcDecreaseNewInv;
    public javax.swing.JComboBox<String> calcDecreaseProductSelect;
    public javax.swing.JLabel calcDecreaseReal;
    public javax.swing.JLabel calcDecreaseTitle;
    public javax.swing.JTextField calcDecreaseUseKg;
    public javax.swing.JButton configButton;
    public javax.swing.JPanel contentLayout;
    private javax.swing.JPanel dashboardView;
    public javax.swing.JButton exitButton;
    public javax.swing.JLabel helloText;
    public javax.swing.JButton helpButton;
    public javax.swing.JButton homeButton;
    public javax.swing.JButton inventoryButton;
    public javax.swing.JButton inventoryReportButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton kitchenReportButton;
    public javax.swing.JTextField newInvKgInitial;
    public javax.swing.JButton newInvProductBtn;
    public javax.swing.JComboBox<String> newInvProductSelect;
    private javax.swing.JPanel newInventory;
    public javax.swing.JLabel newInventoryTitle;
    private javax.swing.JPanel newProduct;
    public javax.swing.JButton newProductBtn;
    public javax.swing.JTextField newProductDecrAvText;
    public javax.swing.JTextField newProductNameText;
    public javax.swing.JTextField newProductPriceText;
    public javax.swing.JComboBox<String> newProductProviderSelect;
    public javax.swing.JLabel newProductTitle;
    private javax.swing.JPanel newProvider;
    public javax.swing.JTextArea newProviderAddressText;
    public javax.swing.JButton newProviderBtn;
    public javax.swing.JTextField newProviderDocText;
    public javax.swing.JTextField newProviderMailText;
    public javax.swing.JTextField newProviderNameText;
    public javax.swing.JTextField newProviderPhoneText;
    public javax.swing.JTextField newProviderSurnameText;
    public javax.swing.JLabel newProviderTitle;
    public javax.swing.JButton newRegistButton;
    public javax.swing.JButton productLoseReportButton;
    public javax.swing.JButton productsButton;
    public javax.swing.JButton providersButton;
    public javax.swing.JTable registerTable;
    public javax.swing.JLabel roleText;
    public javax.swing.JPanel sideBar;
    public javax.swing.JButton supervisorReportButton;
    private javax.swing.JLabel tableRegisterTitle;
    private javax.swing.JPanel tableRegisterView;
    // End of variables declaration//GEN-END:variables
}
