/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author rogerguedez
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    CardLayout cLayout;
    public Screen() {
        initComponents();
        cLayout = (CardLayout) (contentLayout.getLayout());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        productsButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        cutsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        exitButton = new javax.swing.JButton();
        calcButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        kitchenReportButton = new javax.swing.JButton();
        supervisorReportButton = new javax.swing.JButton();
        inventoryReportButton = new javax.swing.JButton();
        productLoseReportButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        providersButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        contentLayout = new javax.swing.JPanel();
        dashboardView = new javax.swing.JPanel();
        tableRegisterView = new javax.swing.JPanel();
        tableRegisterTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(101, 183, 65));

        productsButton.setBackground(new java.awt.Color(101, 183, 65));
        productsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productsButton.setForeground(new java.awt.Color(245, 245, 245));
        productsButton.setText("PRODUCTOS");
        productsButton.setBorderPainted(false);
        productsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsButtonActionPerformed(evt);
            }
        });

        inventoryButton.setBackground(new java.awt.Color(101, 183, 65));
        inventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventoryButton.setForeground(new java.awt.Color(245, 245, 245));
        inventoryButton.setText("INVENTARIO");
        inventoryButton.setBorderPainted(false);
        inventoryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        cutsButton.setBackground(new java.awt.Color(101, 183, 65));
        cutsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cutsButton.setForeground(new java.awt.Color(245, 245, 245));
        cutsButton.setText("CORTES");
        cutsButton.setBorderPainted(false);
        cutsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cutsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutsButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(101, 183, 65));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(245, 245, 245));
        exitButton.setText("SALIR");
        exitButton.setBorderPainted(false);
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        calcButton.setBackground(new java.awt.Color(101, 183, 65));
        calcButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calcButton.setForeground(new java.awt.Color(245, 245, 245));
        calcButton.setText("CALCULAR MERMA");
        calcButton.setBorderPainted(false);
        calcButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        kitchenReportButton.setBackground(new java.awt.Color(101, 183, 65));
        kitchenReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kitchenReportButton.setForeground(new java.awt.Color(245, 245, 245));
        kitchenReportButton.setText("MOVIMIENTOS EN COCINA");
        kitchenReportButton.setBorderPainted(false);
        kitchenReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitchenReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenReportButtonActionPerformed(evt);
            }
        });

        supervisorReportButton.setBackground(new java.awt.Color(101, 183, 65));
        supervisorReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supervisorReportButton.setForeground(new java.awt.Color(245, 245, 245));
        supervisorReportButton.setText("MOVIMIENTOS POR ENCARGADO");
        supervisorReportButton.setBorderPainted(false);
        supervisorReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supervisorReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorReportButtonActionPerformed(evt);
            }
        });

        inventoryReportButton.setBackground(new java.awt.Color(101, 183, 65));
        inventoryReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventoryReportButton.setForeground(new java.awt.Color(245, 245, 245));
        inventoryReportButton.setText("MOVIMIENTOS DE INVENTARIO");
        inventoryReportButton.setBorderPainted(false);
        inventoryReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryReportButtonActionPerformed(evt);
            }
        });

        productLoseReportButton.setBackground(new java.awt.Color(101, 183, 65));
        productLoseReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productLoseReportButton.setForeground(new java.awt.Color(245, 245, 245));
        productLoseReportButton.setText("MERMA POR PRODUCTO");
        productLoseReportButton.setBorderPainted(false);
        productLoseReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productLoseReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productLoseReportButtonActionPerformed(evt);
            }
        });

        configButton.setBackground(new java.awt.Color(101, 183, 65));
        configButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        configButton.setForeground(new java.awt.Color(245, 245, 245));
        configButton.setText("MANTENIMIENTO");
        configButton.setBorderPainted(false);
        configButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(101, 183, 65));
        helpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(245, 245, 245));
        helpButton.setText("AYUDA");
        helpButton.setBorderPainted(false);
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        providersButton.setBackground(new java.awt.Color(101, 183, 65));
        providersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        providersButton.setForeground(new java.awt.Color(245, 245, 245));
        providersButton.setText("PROVEEDORES");
        providersButton.setBorderPainted(false);
        providersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        providersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providersButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(101, 183, 65));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(245, 245, 245));
        homeButton.setText("TABLERO");
        homeButton.setBorderPainted(false);
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(cutsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(calcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(kitchenReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(supervisorReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(inventoryReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(configButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(productLoseReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(providersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cutsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(providersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(kitchenReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supervisorReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLoseReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(configButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        contentLayout.setBackground(new java.awt.Color(255, 255, 255));
        contentLayout.setLayout(new java.awt.CardLayout());

        dashboardView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dashboardViewLayout = new javax.swing.GroupLayout(dashboardView);
        dashboardView.setLayout(dashboardViewLayout);
        dashboardViewLayout.setHorizontalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        dashboardViewLayout.setVerticalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );

        contentLayout.add(dashboardView, "dashboardView");

        tableRegisterView.setBackground(new java.awt.Color(255, 255, 255));

        tableRegisterTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tableRegisterTitle.setForeground(new java.awt.Color(51, 51, 51));
        tableRegisterTitle.setText("Titulo");
        tableRegisterTitle.setMaximumSize(new java.awt.Dimension(550, 512));

        javax.swing.GroupLayout tableRegisterViewLayout = new javax.swing.GroupLayout(tableRegisterView);
        tableRegisterView.setLayout(tableRegisterViewLayout);
        tableRegisterViewLayout.setHorizontalGroup(
            tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableRegisterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(739, Short.MAX_VALUE))
        );
        tableRegisterViewLayout.setVerticalGroup(
            tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableRegisterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(816, Short.MAX_VALUE))
        );

        contentLayout.add(tableRegisterView, "tableRegisterView");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void kitchenReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitchenReportButtonActionPerformed

    private void supervisorReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervisorReportButtonActionPerformed

    private void inventoryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryReportButtonActionPerformed

    private void productLoseReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productLoseReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productLoseReportButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtonActionPerformed

    private void providersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providersButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        tableRegisterTitle.setText("Proveedores");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/providers.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
        System.out.println(tableRegisterTitle.getIcon());
        /*
        contentLayout.removeAll();
        contentLayout.add(dashboardView);
        contentLayout.repaint();
        contentLayout.revalidate();
        */
    }//GEN-LAST:event_providersButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "dashboardView");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void productsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        tableRegisterTitle.setText("Productos");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/products.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_productsButtonActionPerformed

    private void cutsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutsButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        tableRegisterTitle.setText("Cortes");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/cuts.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_cutsButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        tableRegisterTitle.setText("Inventario");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/inventory.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        tableRegisterTitle.setText("Calcular merma");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/calc.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_calcButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private javax.swing.JButton configButton;
    private javax.swing.JPanel contentLayout;
    private javax.swing.JButton cutsButton;
    private javax.swing.JPanel dashboardView;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JButton inventoryReportButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton kitchenReportButton;
    private javax.swing.JButton productLoseReportButton;
    private javax.swing.JButton productsButton;
    private javax.swing.JButton providersButton;
    private javax.swing.JPanel sideBar;
    private javax.swing.JButton supervisorReportButton;
    private javax.swing.JLabel tableRegisterTitle;
    private javax.swing.JPanel tableRegisterView;
    // End of variables declaration//GEN-END:variables
}
