
package view;
import java.awt.CardLayout;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import model.Model;
/**
 *
 * @author rogerguedez
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public CardLayout cLayout;
    String currentView;
    ImageIcon currentImageIcon;
    public Screen() {
        initComponents();
        cLayout = (CardLayout) (contentLayout.getLayout());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        sideBar = new javax.swing.JPanel();
        productsButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        exitButton = new javax.swing.JButton();
        calcButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        kitchenReportButton = new javax.swing.JButton();
        supervisorReportButton = new javax.swing.JButton();
        inventoryReportButton = new javax.swing.JButton();
        productLoseReportButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        providersButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        contentLayout = new javax.swing.JPanel();
        dashboardView = new javax.swing.JPanel();
        tableRegisterView = new javax.swing.JPanel();
        tableRegisterTitle = new javax.swing.JLabel();
        newRegistButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registerTable = new javax.swing.JTable();
        newProvider = new javax.swing.JPanel();
        newProviderTitle = new javax.swing.JLabel();
        newProviderDocText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newProviderNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newProviderSurnameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        newProviderPhoneText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newProviderMailText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        newProviderAddressText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        newProviderBtn = new javax.swing.JButton();
        newProduct = new javax.swing.JPanel();
        newProductTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newProductNameText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newProductPriceText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        newProductDecrAvText = new javax.swing.JTextField();
        newProductBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        newProductProviderSelect = new javax.swing.JComboBox<>();
        newCut = new javax.swing.JPanel();
        newCutTitle = new javax.swing.JLabel();
        newInventory = new javax.swing.JPanel();
        newInventoryTitle = new javax.swing.JLabel();
        newCalc = new javax.swing.JPanel();
        newCalcTitle = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(101, 183, 65));

        productsButton.setBackground(new java.awt.Color(101, 183, 65));
        productsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productsButton.setForeground(new java.awt.Color(245, 245, 245));
        productsButton.setText("PRODUCTOS");
        productsButton.setBorderPainted(false);
        productsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productsButton.setName("Product"); // NOI18N
        productsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsButtonActionPerformed(evt);
            }
        });

        inventoryButton.setBackground(new java.awt.Color(101, 183, 65));
        inventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventoryButton.setForeground(new java.awt.Color(245, 245, 245));
        inventoryButton.setText("INVENTARIO");
        inventoryButton.setBorderPainted(false);
        inventoryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryButton.setName("Inventory"); // NOI18N
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(101, 183, 65));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(245, 245, 245));
        exitButton.setText("SALIR");
        exitButton.setBorderPainted(false);
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        calcButton.setBackground(new java.awt.Color(101, 183, 65));
        calcButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calcButton.setForeground(new java.awt.Color(245, 245, 245));
        calcButton.setText("CALCULAR MERMA");
        calcButton.setBorderPainted(false);
        calcButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calcButton.setName("Calc"); // NOI18N
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        kitchenReportButton.setBackground(new java.awt.Color(101, 183, 65));
        kitchenReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kitchenReportButton.setForeground(new java.awt.Color(245, 245, 245));
        kitchenReportButton.setText("MOVIMIENTOS EN COCINA");
        kitchenReportButton.setBorderPainted(false);
        kitchenReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitchenReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenReportButtonActionPerformed(evt);
            }
        });

        supervisorReportButton.setBackground(new java.awt.Color(101, 183, 65));
        supervisorReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supervisorReportButton.setForeground(new java.awt.Color(245, 245, 245));
        supervisorReportButton.setText("MOVIMIENTOS POR ENCARGADO");
        supervisorReportButton.setBorderPainted(false);
        supervisorReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supervisorReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorReportButtonActionPerformed(evt);
            }
        });

        inventoryReportButton.setBackground(new java.awt.Color(101, 183, 65));
        inventoryReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventoryReportButton.setForeground(new java.awt.Color(245, 245, 245));
        inventoryReportButton.setText("MOVIMIENTOS DE INVENTARIO");
        inventoryReportButton.setBorderPainted(false);
        inventoryReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryReportButtonActionPerformed(evt);
            }
        });

        productLoseReportButton.setBackground(new java.awt.Color(101, 183, 65));
        productLoseReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productLoseReportButton.setForeground(new java.awt.Color(245, 245, 245));
        productLoseReportButton.setText("MERMA POR PRODUCTO");
        productLoseReportButton.setBorderPainted(false);
        productLoseReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productLoseReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productLoseReportButtonActionPerformed(evt);
            }
        });

        configButton.setBackground(new java.awt.Color(101, 183, 65));
        configButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        configButton.setForeground(new java.awt.Color(245, 245, 245));
        configButton.setText("MANTENIMIENTO");
        configButton.setBorderPainted(false);
        configButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(101, 183, 65));
        helpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(245, 245, 245));
        helpButton.setText("AYUDA");
        helpButton.setBorderPainted(false);
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        providersButton.setBackground(new java.awt.Color(101, 183, 65));
        providersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        providersButton.setForeground(new java.awt.Color(245, 245, 245));
        providersButton.setText("PROVEEDORES");
        providersButton.setBorderPainted(false);
        providersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        providersButton.setName("Provider"); // NOI18N
        providersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providersButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(101, 183, 65));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(245, 245, 245));
        homeButton.setText("TABLERO");
        homeButton.setBorderPainted(false);
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(calcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(kitchenReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(supervisorReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(inventoryReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(configButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(productLoseReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(providersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(providersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(kitchenReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supervisorReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLoseReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(configButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contentLayout.setBackground(new java.awt.Color(255, 255, 255));
        contentLayout.setLayout(new java.awt.CardLayout());

        dashboardView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dashboardViewLayout = new javax.swing.GroupLayout(dashboardView);
        dashboardView.setLayout(dashboardViewLayout);
        dashboardViewLayout.setHorizontalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        dashboardViewLayout.setVerticalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );

        contentLayout.add(dashboardView, "dashboardView");

        tableRegisterView.setBackground(new java.awt.Color(255, 255, 255));

        tableRegisterTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tableRegisterTitle.setForeground(new java.awt.Color(51, 51, 51));
        tableRegisterTitle.setText("Titulo");
        tableRegisterTitle.setMaximumSize(new java.awt.Dimension(550, 512));

        newRegistButton.setBackground(new java.awt.Color(101, 183, 65));
        newRegistButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newRegistButton.setForeground(new java.awt.Color(245, 245, 245));
        newRegistButton.setText("NUEVO");
        newRegistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRegistButtonActionPerformed(evt);
            }
        });

        registerTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(registerTable);

        javax.swing.GroupLayout tableRegisterViewLayout = new javax.swing.GroupLayout(tableRegisterView);
        tableRegisterView.setLayout(tableRegisterViewLayout);
        tableRegisterViewLayout.setHorizontalGroup(
            tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableRegisterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tableRegisterViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tableRegisterViewLayout.createSequentialGroup()
                        .addComponent(tableRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 638, Short.MAX_VALUE)
                        .addComponent(newRegistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        tableRegisterViewLayout.setVerticalGroup(
            tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableRegisterViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableRegisterViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newRegistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        contentLayout.add(tableRegisterView, "tableRegisterView");

        newProvider.setBackground(new java.awt.Color(255, 255, 255));
        newProvider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newProvider.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newProviderTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newProviderTitle.setForeground(new java.awt.Color(51, 51, 51));
        newProviderTitle.setText("Nuevo proveedor");
        newProviderTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newProviderTitle.setName("newProductTitle"); // NOI18N

        newProviderDocText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderDocText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderDocTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Rif/Cédula");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        newProviderNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderNameTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");

        newProviderSurnameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderSurnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderSurnameTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Teléfono");

        newProviderPhoneText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderPhoneTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Correo");

        newProviderMailText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderMailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProviderMailTextActionPerformed(evt);
            }
        });

        newProviderAddressText.setColumns(20);
        newProviderAddressText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProviderAddressText.setRows(5);
        jScrollPane2.setViewportView(newProviderAddressText);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Dirección");

        newProviderBtn.setBackground(new java.awt.Color(255, 181, 52));
        newProviderBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newProviderBtn.setForeground(new java.awt.Color(245, 245, 245));
        newProviderBtn.setText("GUARDAR");

        javax.swing.GroupLayout newProviderLayout = new javax.swing.GroupLayout(newProvider);
        newProvider.setLayout(newProviderLayout);
        newProviderLayout.setHorizontalGroup(
            newProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProviderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newProviderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProviderDocText)
                    .addComponent(jLabel1)
                    .addComponent(newProviderNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(newProviderSurnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(newProviderPhoneText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(newProviderMailText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProviderLayout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addComponent(newProviderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        newProviderLayout.setVerticalGroup(
            newProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProviderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newProviderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderDocText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderSurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProviderMailText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(newProviderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        contentLayout.add(newProvider, "newProvider");

        newProduct.setBackground(new java.awt.Color(255, 255, 255));
        newProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newProduct.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newProductTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newProductTitle.setForeground(new java.awt.Color(51, 51, 51));
        newProductTitle.setText("Nuevo producto");
        newProductTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newProductTitle.setName("newProductTitle"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre");

        newProductNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductNameTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Precio");

        newProductPriceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductPriceTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Merma Promedio");

        newProductDecrAvText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductDecrAvText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductDecrAvTextActionPerformed(evt);
            }
        });

        newProductBtn.setBackground(new java.awt.Color(255, 181, 52));
        newProductBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newProductBtn.setForeground(new java.awt.Color(245, 245, 245));
        newProductBtn.setText("GUARDAR");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Proveedor");

        newProductProviderSelect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout newProductLayout = new javax.swing.GroupLayout(newProduct);
        newProduct.setLayout(newProductLayout);
        newProductLayout.setHorizontalGroup(
            newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newProductLayout.createSequentialGroup()
                .addContainerGap(452, Short.MAX_VALUE)
                .addComponent(newProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
            .addGroup(newProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newProductProviderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newProductNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(newProductPriceText)
                        .addComponent(jLabel8)
                        .addComponent(newProductDecrAvText)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newProductLayout.setVerticalGroup(
            newProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProductNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProductPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProductDecrAvText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(newProductProviderSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(newProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        contentLayout.add(newProduct, "newProduct");

        newCut.setBackground(new java.awt.Color(255, 255, 255));
        newCut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newCut.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newCutTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newCutTitle.setForeground(new java.awt.Color(51, 51, 51));
        newCutTitle.setText("Nuevo producto");
        newCutTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newCutTitle.setName("newProductTitle"); // NOI18N

        javax.swing.GroupLayout newCutLayout = new javax.swing.GroupLayout(newCut);
        newCut.setLayout(newCutLayout);
        newCutLayout.setHorizontalGroup(
            newCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(659, Short.MAX_VALUE))
        );
        newCutLayout.setVerticalGroup(
            newCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(816, Short.MAX_VALUE))
        );

        contentLayout.add(newCut, "newCut");

        newInventory.setBackground(new java.awt.Color(255, 255, 255));
        newInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newInventory.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newInventoryTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newInventoryTitle.setForeground(new java.awt.Color(51, 51, 51));
        newInventoryTitle.setText("Nuevo producto");
        newInventoryTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newInventoryTitle.setName("newProductTitle"); // NOI18N

        javax.swing.GroupLayout newInventoryLayout = new javax.swing.GroupLayout(newInventory);
        newInventory.setLayout(newInventoryLayout);
        newInventoryLayout.setHorizontalGroup(
            newInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newInventoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(659, Short.MAX_VALUE))
        );
        newInventoryLayout.setVerticalGroup(
            newInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newInventoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(816, Short.MAX_VALUE))
        );

        contentLayout.add(newInventory, "newInventory");

        newCalc.setBackground(new java.awt.Color(255, 255, 255));
        newCalc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newCalc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        newCalcTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        newCalcTitle.setForeground(new java.awt.Color(51, 51, 51));
        newCalcTitle.setText("Nuevo producto");
        newCalcTitle.setMaximumSize(new java.awt.Dimension(550, 512));
        newCalcTitle.setName("newProductTitle"); // NOI18N

        javax.swing.GroupLayout newCalcLayout = new javax.swing.GroupLayout(newCalc);
        newCalc.setLayout(newCalcLayout);
        newCalcLayout.setHorizontalGroup(
            newCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCalcTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(659, Short.MAX_VALUE))
        );
        newCalcLayout.setVerticalGroup(
            newCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCalcTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(816, Short.MAX_VALUE))
        );

        contentLayout.add(newCalc, "newCalc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void kitchenReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitchenReportButtonActionPerformed

    private void supervisorReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervisorReportButtonActionPerformed

    private void inventoryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryReportButtonActionPerformed

    private void productLoseReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productLoseReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productLoseReportButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtonActionPerformed

    private void providersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providersButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        tableRegisterTitle.setText("Proveedores");
        currentView = providersButton.getName();
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconProvider.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
        System.out.println(tableRegisterTitle.getIcon());
        /*
        contentLayout.removeAll();
        contentLayout.add(dashboardView);
        contentLayout.repaint();
        contentLayout.revalidate();
        */
    }//GEN-LAST:event_providersButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "dashboardView");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void productsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        currentView = productsButton.getName();
        
        tableRegisterTitle.setText("Productos");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconProduct.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_productsButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        currentView = inventoryButton.getName();
        tableRegisterTitle.setText("Inventario");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconInventory.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
        cLayout.show(contentLayout, "tableRegisterView");
        currentView = calcButton.getName();
        tableRegisterTitle.setText("Calcular merma");
        tableRegisterTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconCalc.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_calcButtonActionPerformed

    private void newRegistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRegistButtonActionPerformed
        // TODO add your handling code here:
        Model m = new Model();
        cLayout.show(contentLayout, "new"+currentView);
        switch (currentView){
            case "Product":
                newProductTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconProduct.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
            case "Provider":
                newProviderTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconProvider.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
        {
            try {
                ResultSet rs = m.getProviders();
                
                DefaultComboBoxModel boxModel = new DefaultComboBoxModel();
                while (rs.next()) {
                        //newProductProviderSelect.a (new ComboItem(rs.getString("rif")+ " " + rs.getString("nombre"), rs.getInt("id_proveedor")));
                        //USEN ESTE MÉTODO
                        
                        boxModel.addElement(new ComboItem(rs.getString("rif")+ " " + rs.getString("nombre"), rs.getString("id_proveedor")));
    
                   }
                newProductProviderSelect.setModel(boxModel);
 
            } catch (SQLException ex) {
                Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            case "Inventory":
                newInventoryTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconInventory.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
            case "Calc":
                newCalcTitle.setIcon(new ImageIcon(new ImageIcon("./src/imgs/iconCalc.png").getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
        
        }
    }//GEN-LAST:event_newRegistButtonActionPerformed

    private void newProviderDocTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderDocTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderDocTextActionPerformed

    private void newProviderNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderNameTextActionPerformed

    private void newProviderSurnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderSurnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderSurnameTextActionPerformed

    private void newProviderPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderPhoneTextActionPerformed

    private void newProviderMailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProviderMailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProviderMailTextActionPerformed

    private void newProductNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductNameTextActionPerformed

    private void newProductPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductPriceTextActionPerformed

    private void newProductDecrAvTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductDecrAvTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductDecrAvTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private javax.swing.JButton configButton;
    public javax.swing.JPanel contentLayout;
    private javax.swing.JPanel dashboardView;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JButton inventoryReportButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton kitchenReportButton;
    private javax.swing.JPanel newCalc;
    private javax.swing.JLabel newCalcTitle;
    private javax.swing.JPanel newCut;
    private javax.swing.JLabel newCutTitle;
    private javax.swing.JPanel newInventory;
    private javax.swing.JLabel newInventoryTitle;
    private javax.swing.JPanel newProduct;
    public javax.swing.JButton newProductBtn;
    public javax.swing.JTextField newProductDecrAvText;
    public javax.swing.JTextField newProductNameText;
    public javax.swing.JTextField newProductPriceText;
    public javax.swing.JComboBox<String> newProductProviderSelect;
    private javax.swing.JLabel newProductTitle;
    private javax.swing.JPanel newProvider;
    public javax.swing.JTextArea newProviderAddressText;
    public javax.swing.JButton newProviderBtn;
    public javax.swing.JTextField newProviderDocText;
    public javax.swing.JTextField newProviderMailText;
    public javax.swing.JTextField newProviderNameText;
    public javax.swing.JTextField newProviderPhoneText;
    public javax.swing.JTextField newProviderSurnameText;
    private javax.swing.JLabel newProviderTitle;
    private javax.swing.JButton newRegistButton;
    private javax.swing.JButton productLoseReportButton;
    public javax.swing.JButton productsButton;
    public javax.swing.JButton providersButton;
    public javax.swing.JTable registerTable;
    private javax.swing.JPanel sideBar;
    private javax.swing.JButton supervisorReportButton;
    private javax.swing.JLabel tableRegisterTitle;
    private javax.swing.JPanel tableRegisterView;
    // End of variables declaration//GEN-END:variables
}
